IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Class')
BEGIN
    CREATE TABLE Class (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Name VARCHAR(100) NOT NULL,
        GradeId INT NOT NULL,
        StartDate DATETIME,
        EndDate DATETIME,
        FOREIGN KEY (GradeId) REFERENCES Grade(Id)
    );
END