IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'UsersRoles')
BEGIN
    CREATE TABLE UsersRoles (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        FOREIGN KEY (UserId) REFERENCES [User](Id),
        RoleId INT NOT NULL,
        FOREIGN KEY (RoleId) REFERENCES Role(Id)
    );
END