IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Student' AND COLUMN_NAME = 'GradeId' )
BEGIN
    ALTER TABLE Student DROP CONSTRAINT FK__Student__ClassId__34C8D9D1; 
    ALTER TABLE Student DROP COLUMN ClassId;
    ALTER TABLE Student ADD GradeId INT;
    ALTER TABLE Student ADD FOREIGN KEY (GradeId) REFERENCES Grade(Id);
END