IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Student' AND COLUMN_NAME = 'GradeCourseId' )
BEGIN
    ALTER TABLE Student DROP CONSTRAINT FK__Student__GradeId__4E88ABD4;
    ALTER TABLE Student DROP COLUMN GradeId;
    ALTER TABLE Student ADD GradeCourseId INT;
    ALTER TABLE Student ADD FOREIGN KEY (GradeCourseId) REFERENCES GradeCourse(Id);
END