IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'Grade')
BEGIN
    CREATE TABLE Grade (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Name VARCHAR(100) NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'Level')
BEGIN
    CREATE TABLE Level (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Name VARCHAR(100) NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'Course')
BEGIN
    CREATE TABLE Course (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        CourseName VARCHAR(20) NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'GradeCourse')
BEGIN
    CREATE TABLE GradeCourse (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        GradeId INT NOT NULL,
        FOREIGN KEY (GradeId) REFERENCES Grade(Id),
        CourseId INT NOT NULL,
        FOREIGN KEY (CourseId) REFERENCES Course(Id)
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'Class')
BEGIN
    CREATE TABLE Class (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Name VARCHAR(100) NOT NULL,
        GradeCourseId INT NOT NULL,
        FOREIGN KEY (GradeCourseId) REFERENCES GradeCourse(Id),
        LevelId INT NOT NULL,
        FOREIGN KEY (LevelId) REFERENCES Level(Id),
        StartDate DATETIME,
        EndDate DATETIME,
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Student')
BEGIN
    CREATE TABLE Student (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        EnglishName VARCHAR(20) NOT NULL,
        Surname VARCHAR(20),
        ChineseName VARCHAR(50),
        ClassId INT,
        FOREIGN KEY (ClassId) REFERENCES Class(Id)
    );
END


