version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend

  api:
    build:
      context: ./API/CMApi
      dockerfile: Dockerfile
    # Other configurations for your .NET API service

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    # Other configurations for your frontend service

networks:
  your_custom_network:
    name: your_custom_network
    external: true