swagger: "2.0"
info:
  title: Class Management API
  version: 1.0.0
  description: A mock API for the fullstack app.
paths:
  /grades:
    get:
      summary: Get a list of all the grades
      responses:
        '200':
          description: A list of grades
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      description: The unique ID of the grade
                    Name:
                      type: string
                      description: The name of the grade
    post:
      summary: Create a new grade
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Name:
                  type: string
                  description: The name of the grade
              required:
                - Name
      responses:
        '201':
          description: The newly created grade
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The unique ID of the new grade
  /grades/{id}:
    get:
      summary: Get a grade by ID
      parameters:
        - name: id
          in: path
          description: The ID of the to-do grade to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The requested grade
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The unique ID of the grade
                  Name:
                    type: string
                    description: The name of the grade
        '404':
          description: grade item not found
